CREATE TABLE item (
	id BIGINT PRIMARY KEY,
	codigo VARCHAR(8) NOT NULL,
	titulo VARCHAR(100) NOT NULL,
	tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('LIVRO', 'REVISTA')),
	autor VARCHAR(100) NOT NULL,
	edicao VARCHAR(100) NOT NULL,
	disponivel BOOLEAN NOT NULL DEFAULT true
);



